//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealGaz.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealGaz.Resources.Translator", typeof(Translator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენს შესახებ.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealGaz გაზის გაყიდვის მიმართულებით 15 წელია მუშაობს აზერბაიჯანულ ბაზარზე. კომპანია დაკავებულია საწარმოო, ტექნიკური, სამედიცინო და სპეციალიზირებული გაზების გაყიდვით და მომსახურებით, აგრეთვე სხვადასხვა გაზის შენაერთებით. კომპანიას გააჩნია საკუთარი ლაბორატორია, სადაც შესაძლებელია ყველა გაზის ანალიზი, რომელიც იწარმოება ჩვენს ქარხანაში და გვაქვს გაყიდვისთვის. წარმოების უფრო დიდი წარმადობისთვის და გაყიდვების ინტეგრირებული ქსელისთვის RealGaz ცდილობს აწარმოოს ნედლეულის სწრაფი მიწოდება აზერბაიჯანის ტერიტორიის ნების [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კომენტარი.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საკონტაქტო ფორმა.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კონტაქტი.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ-ფოსტა.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შემოგვიერთდით.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მთავარი.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მობილური.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქართველო, ქ. თბილისი, დავით ბაქრაძის 6, სართული 8.
        /// </summary>
        public static string OfficeAddress {
            get {
                return ResourceManager.GetString("OfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომსახურება.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენ გაგავაჩნია  კოლეკტორის და კოლექტორის გარეშე სახმელეთო და საზღვაო გადაზიდვების სპეციალიზირებული გაზის ცილინდრების სადგარები: 12, 16, 48 ან 64 ცილინდრიანი, 150, 200 და 300 ატმოსფერული წნევით, 40  და 50 ლ. მოცულობით. ყველა სადგარები დამზადებულია ჩვენს წარმოებაში, გათვლილია ჩვენი კომპანიისთვის და შეესაბამება DNV 2.7.1 სტანდარტს. სადგარები წელიწადში ერთხელ ექვემდებარება სერტიფიცირებას. გავაქვს სადგარები ჟანგბადის, არგონის, არგონის მინარევების, აზოტის, ნახშირორჟანგის, პროპანის, აცეტილენის და ჰელიუმის ცილინდრ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OurServicesText_Col1_Content {
            get {
                return ResourceManager.GetString("OurServicesText_Col1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაზის ცილინდრების სადგარები.
        /// </summary>
        public static string OurServicesText_Col1_Header {
            get {
                return ResourceManager.GetString("OurServicesText_Col1_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენ კომპანიას საგანგებო სიტუაციების სამინისტროსგან მიღებული აქვს ნებართვა გაზის ცილინდრების ჰიდროტესტზე, რაც იძლევა მათი გამოყენების გარანტიას 5 წლის განმავლობაში. ამ ტესტის შედეგებზე დაყრდნობით ჩვენ ვუზრუნველყოფთ სათანადო სერტიფიკატს ყველა ჩვენს ცილინდრსა და ჩვენს მომხმარებელთა ცილინდრებზე. ჩვენ ასევე ვახორციელებთ ცილინდრების ღებვას გაზის ტიპების კოდირებით, დაზიანებული სარქველების გამოცვლას, აღდგენას და შეკეთებას. ჩვენ მომხმარებელს ვაწვდით გაზებს მხოლოდ ტესტირებული ცილინდრებით და შესაბამისი სერთიფიკატებით [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OurServicesText_Col2_Content {
            get {
                return ResourceManager.GetString("OurServicesText_Col2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ოპერაციები გაზის ცილინდრებზე.
        /// </summary>
        public static string OurServicesText_Col2_Header {
            get {
                return ResourceManager.GetString("OurServicesText_Col2_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კომპანიას გააჩნია ლიცენზია საშიში ტვირთების გადაზიდვაზე და ვუზრუნველყოფთ გაზის ბალონების მიწოდებას ადგილზე, კლიენტის მოთხოვნის შესაბამისად. ამ მიზნით, გამოიყენება სპეციალურად მოწყობილი სატრანსპორტო საშუალებები  ადგილობრივი ხელისუფლებისა და მომხმარებლების მოთხოვნების შესაბამისად. გარდა ამისა, ჩვენ გვყავს სპეციალური სატრანსპორტო საშუალებები LIN, LXX და LAR- ის  14 მ 3-ის მოცულობით მიწოდებისთვის..
        /// </summary>
        public static string OurServicesText_Col3_Content {
            get {
                return ResourceManager.GetString("OurServicesText_Col3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანსპორტირება.
        /// </summary>
        public static string OurServicesText_Col3_Header {
            get {
                return ResourceManager.GetString("OurServicesText_Col3_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩვენ ვუზრუნველყოფთ ნებისმიერი ტიპის გამოყენებული გაზის ცილინდრების ამოღებას საწარმოებიდან და მათ უტილიზაციას. ვიღებთ შეკვეთებს გაზის, ცეცხლმაქრი, გამაციებელი და სხვა ტიპის ცილინდრების უტილიზაციაზე. ცილინდრებს ეხსნება სარქველები, სუფთავდება შიგთავსში დარჩენილი გაზისგან და  ზიანდება ისე, რომ ასეთი სახით შემდგომში გამოყენება ვერ შეძლოს ვერავინ. უტილიზირებული ცილინდრები ან უბრუნდება დამკვეთს, ან ბარდება ჯართში..
        /// </summary>
        public static string OurServicesText_Col4_Content {
            get {
                return ResourceManager.GetString("OurServicesText_Col4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გამოყენებული ცილინდრების უტილიზაცია.
        /// </summary>
        public static string OurServicesText_Col4_Header {
            get {
                return ResourceManager.GetString("OurServicesText_Col4_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონი.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პროდუქტები.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetylene.
        /// </summary>
        public static string Products_Acetylene_Header {
            get {
                return ResourceManager.GetString("Products_Acetylene_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetylene (systematic name: ethyne) is the chemical compound with the formula QHj. It is a hydrocarbon and the simplest alkyne. This colorless gas is widely used as a fuel and a chemical building block. It is unstable in pure form and thus is usually handled as a solution.Pure acetylene is odorless, but commercial grades usually have a marked odor due to impurities.
        ///Approximately 20 percent of acetylene is supplied by the industrial gases industry for oxyacetylene gas welding and cutting due to the high te [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_Acetylene_Large_Content {
            get {
                return ResourceManager.GetString("Products_Acetylene_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acetylene (systematic name: ethyne) is the chemical compound with the formula QHj. It is a hydrocarbon and the simplest alkyne. This colorless gas is widely used as a fuel and a ch....
        /// </summary>
        public static string Products_Acetylene_Small_Content {
            get {
                return ResourceManager.GetString("Products_Acetylene_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argon.
        /// </summary>
        public static string Products_Argon_Header {
            get {
                return ResourceManager.GetString("Products_Argon_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most common gas in the Earth&apos;s atmosphere, at 0.93% (9,300 ppm), making it approximately 23.8 times as abundant as the next most common atmospheric gas, carbon dioxide (390 ppm), and more than 500 times as abundant as the next most common noble gas, neon (18 ppm). Nearly all of this argon is radiogenic argon-40derived from the decay of potassium-40 in the Earth&apos;s cr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_Argon_Large_Content {
            get {
                return ResourceManager.GetString("Products_Argon_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas. Argon is the third most abundant gas in the Earth&apos;s atm....
        /// </summary>
        public static string Products_Argon_Small_Content {
            get {
                return ResourceManager.GetString("Products_Argon_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argon-carbon dioxide.
        /// </summary>
        public static string Products_ArgonCarbonDioxide_Header {
            get {
                return ResourceManager.GetString("Products_ArgonCarbonDioxide_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © C-50 (50% argon/50% C02) is used for short arc welding of pipes,
        ///® C-40 (60% argon/40% C02) is used for some flux-cored arc welding cases. Better weld penetration than C-25.
        ///© C-25 (75% argon/25% C02) is commonly used by hobbyists and in small-scale production.
        ///Limited to short circuit and globular transfer welding. Common for short-circuit gas metal arc welding of low carbon steel.
        ///© C-20 (80% argon/20% C02) is used for short-circuiting and spray transfer of carbon steel.
        ///© C-15 (85% argon/15% C02)  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_ArgonCarbonDioxide_Large_Content {
            get {
                return ResourceManager.GetString("Products_ArgonCarbonDioxide_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © C-50 (50% argon/50% C02) is used for short arc welding of pipes,
        ///                                        ® C-40 (60% argon/40% C02) is used for some flux-cored arc welding cases. Better weld penetration than C-25.....
        /// </summary>
        public static string Products_ArgonCarbonDioxide_Small_Content {
            get {
                return ResourceManager.GetString("Products_ArgonCarbonDioxide_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon dioxide.
        /// </summary>
        public static string Products_CarbonDioxide_Header {
            get {
                return ResourceManager.GetString("Products_CarbonDioxide_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon dioxide (chemical formula C02) is a naturally-occurring chemical compound composed of 2 oxygen atom seach covalently double bonded to a single carbon atom. It is a gas at standard temperature and pressure and exists in Earth&apos;s atmosphere in this state, as a trace gas at a concentration of 0.04 per cent (400 ppm) by volume, as of 2014. Carbon dioxide is used by the food industry, the oil industry, and the chemical industry.
        ///It is one of the most commonly used compressed gases for pneumatic (pressuriz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_CarbonDioxide_Large_Content {
            get {
                return ResourceManager.GetString("Products_CarbonDioxide_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbon dioxide (chemical formula CO2) is a colorless and odorless gas vital to life on Earth. This naturally occurring chemical compound is composed of a carbon atom covalently dou....
        /// </summary>
        public static string Products_CarbonDioxide_Small_Content {
            get {
                return ResourceManager.GetString("Products_CarbonDioxide_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helium.
        /// </summary>
        public static string Products_Helium_Header {
            get {
                return ResourceManager.GetString("Products_Helium_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table. Its boiling and melting points are the lowest among the elements and it exists only as a gas except in extreme conditions.
        ///Helium is the second lightest element and is the second most abundant element in the observable universe, being present at about 24% of the total elemental mass, which is more than 12 times the mas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_Helium_Large_Content {
            get {
                return ResourceManager.GetString("Products_Helium_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the perio....
        /// </summary>
        public static string Products_Helium_Small_Content {
            get {
                return ResourceManager.GetString("Products_Helium_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აზოტი.
        /// </summary>
        public static string Products_Nitrogen_Header {
            get {
                return ResourceManager.GetString("Products_Nitrogen_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitrogen, symbol N, is the chemical element of atomic number seven. At room temperature, it is a gas diatomic molecules and is colorless and odorless. Nitrogen is a common element in the universe, estimated at about seventh in total abundance in our galaxy and the Solar System. On Earth, the element is primarily found as the gas molecule; it forms about 78% of Earth&apos;s atmosphere. The element nitrogen was discovered as a separable component of air, by Scottish physidan Daniel Rutherford, in 1772.
        ///Many indus [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_Nitrogen_Large_Content {
            get {
                return ResourceManager.GetString("Products_Nitrogen_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აზოტი — ქიმიური ელემენტი, უფერული აირი, რომელსაც არ აქვს სუნი და გემო და ხელს არ უწყობს წვას; ჰაერის ერთ-ერთი ძირითადი შემადგენელი ნაწილია....
        /// </summary>
        public static string Products_Nitrogen_Small_Content {
            get {
                return ResourceManager.GetString("Products_Nitrogen_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჟანგბადი.
        /// </summary>
        public static string Products_Oxygen_Header {
            get {
                return ResourceManager.GetString("Products_Oxygen_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the challogen group on the periodic table and is a highly reactive nonmetallic element and oxidizing agent that readily forms compounds (notablyoxides) with most elements. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium. At STP, two atoms of the element bind to form dioxygen, a diatomic gas that is colorless, odorless, and tasteless, with the formula 02.
        ///Smelting of iron ore into  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_Oxygen_Large_Content {
            get {
                return ResourceManager.GetString("Products_Oxygen_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჟანგბადი არის პეროიდულ ცხრილში ჰალკოგენიდების ჯგუფის წევრი,  მისი რიგითი ნომერია 8 და გამოისახება სიმბოლოთი O (ლათ. Oxygenium) . ჟანგბადი ქიმიურად აქტიური არამეტალია.....
        /// </summary>
        public static string Products_Oxygen_Small_Content {
            get {
                return ResourceManager.GetString("Products_Oxygen_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propane.
        /// </summary>
        public static string Products_Propane_Header {
            get {
                return ResourceManager.GetString("Products_Propane_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propane is a three-carbon alkane with the molecular formula C3H8, normally a gas, but compressible to a transportable liquid. A by-product of natural gas processing and petroleum refining, it is commonly used as a fuel forengines, oxy-gas torches, barbecues, portable stoves, and residential central heating. Propane is one of a group ofliquefled petroleum gases (LP gases). The others include butane, propylene, butadiene, butylene, isobutylene and mixtures thereof.
        ///Propane is a popular choice for barbecues a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products_Propane_Large_Content {
            get {
                return ResourceManager.GetString("Products_Propane_Large_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propan is a three-carbon alkane with the molecular formula C3H8, normally a gas, but compressible to a transportable liquid. A by-product of natural gas processing and petroleum re....
        /// </summary>
        public static string Products_Propane_Small_Content {
            get {
                return ResourceManager.GetString("Products_Propane_Small_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ვრცლად.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაგზავნა.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საქმიანობის სფერო.
        /// </summary>
        public static string WhatWeDo {
            get {
                return ResourceManager.GetString("WhatWeDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ობიექტების შემდეგი სახეობის ტექნიკური გაზებით მომარაგება: არგონი/თხევადი არგონი (Ar) / არგონის ნარევი სხვა გაზებთან, ნახშირორჟანგი / თხევადი ნახშირორჟანგი (CO2), აზოტი / თხევადი აზოტი (N2), ჟანგბადი/თხევადი ჟანგბადი (O2), ჰელიუმი (He), შეკუმშული ჰაერი, წყალბადი(Н2), პროპანი (С3Н8), აცეტილენი (С2Н2), კალიბრირებული გაზები და სხვ..
        /// </summary>
        public static string WhatWeDo_01_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_01_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაზის მიწოდება.
        /// </summary>
        public static string WhatWeDo_01_Header {
            get {
                return ResourceManager.GetString("WhatWeDo_01_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაზის ცილინდრების გაყიდვა და მიწოდება.
        /// </summary>
        public static string WhatWeDo_02_Header {
            get {
                return ResourceManager.GetString("WhatWeDo_02_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * სხვადასხვა მოცულობები: 10-დან 50 ლიტრამდე.
        /// </summary>
        public static string WhatWeDo_02_Row1_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_02_Row1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * მუშა წნევები: 150 ატმოსფერო, 200 ატმ, 230 ატმ, 300 ატმ..
        /// </summary>
        public static string WhatWeDo_02_Row2_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_02_Row2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ცილინდრებთან დაკავშირებული ოპერაციები.
        /// </summary>
        public static string WhatWeDo_03_Header {
            get {
                return ResourceManager.GetString("WhatWeDo_03_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * დათვალიერება.
        /// </summary>
        public static string WhatWeDo_03_Row1_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_03_Row1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * ჰიდროგამოცდა.
        /// </summary>
        public static string WhatWeDo_03_Row2_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_03_Row2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * აღდგენა.
        /// </summary>
        public static string WhatWeDo_03_Row3_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_03_Row3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * რემონტი.
        /// </summary>
        public static string WhatWeDo_03_Row4_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_03_Row4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * შეღებვა.
        /// </summary>
        public static string WhatWeDo_03_Row5_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_03_Row5_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * სერტიფიცირება.
        /// </summary>
        public static string WhatWeDo_03_Row6_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_03_Row6_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაზის აქსესუარების გაყიდვა.
        /// </summary>
        public static string WhatWeDo_04_Header {
            get {
                return ResourceManager.GetString("WhatWeDo_04_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * გაზის რეგულატორები.
        /// </summary>
        public static string WhatWeDo_04_Row1_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_04_Row1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * მილები.
        /// </summary>
        public static string WhatWeDo_04_Row2_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_04_Row2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * დამხმარე ხელსაწყოები.
        /// </summary>
        public static string WhatWeDo_04_Row3_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_04_Row3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * კლაპნები.
        /// </summary>
        public static string WhatWeDo_04_Row4_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_04_Row4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * შედუღების აგრეგატები: მჭრელები, გამაცხელებლები, ინჟექტორები და ა. შ..
        /// </summary>
        public static string WhatWeDo_04_Row5_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_04_Row5_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სხვა მომსახურება.
        /// </summary>
        public static string WhatWeDo_05_Header {
            get {
                return ResourceManager.GetString("WhatWeDo_05_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * სახიფათო ტვირთების ტრანსპორტირება.
        /// </summary>
        public static string WhatWeDo_05_Row1_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_05_Row1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * ჩამოწერილი ცილინდრების უტილიზაცია.
        /// </summary>
        public static string WhatWeDo_05_Row2_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_05_Row2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * მშრალი ყინულის მიწოდება.
        /// </summary>
        public static string WhatWeDo_05_Row3_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_05_Row3_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * გამაციებელი ნივთიერებების მიწოდება.
        /// </summary>
        public static string WhatWeDo_05_Row4_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_05_Row4_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to წარმოების პროცესი.
        /// </summary>
        public static string WhatWeDo_06_Header {
            get {
                return ResourceManager.GetString("WhatWeDo_06_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * გაზის ცილინდრების გალიების პროექტირება, დამზადება და მიწოდება.
        /// </summary>
        public static string WhatWeDo_06_Row1_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_06_Row1_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * მონობლოკების პროექტირება, მონტაჟი, ტესტირება და ექსპლუატაციაში დანერგვა.
        /// </summary>
        public static string WhatWeDo_06_Row2_Content {
            get {
                return ResourceManager.GetString("WhatWeDo_06_Row2_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მომსახურების სფერო, რომელსაც გთავაზობთ RealGaz.
        /// </summary>
        public static string WhatWeDoSubHeader {
            get {
                return ResourceManager.GetString("WhatWeDoSubHeader", resourceCulture);
            }
        }
    }
}
